# Generated by Django 5.0.3 on 2024-05-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('contact', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('psw', models.CharField(default='', max_length=50)),
                ('psw2', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('contact', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
