# Generated by Django 5.0.3 on 2024-05-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='psw',
            new_name='Password',
        ),
    ]
