# Generated by Django 5.0.3 on 2024-05-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_psw_admission_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='psw2',
            new_name='pass01',
        ),
    ]
